apiVersion: batch/v1
kind: Job
metadata:
  name: nodejs-todo-job
spec:
  template:
    spec:
      containers:
      - name: nodejs-todo-job
        image: yash5090/nodejs-todo:latest
        ports:
        - containerPort: 3000
      restartPolicy: OnFailure
