apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-todo-deployment
spec:
  replicas: 6 # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nodejs-todo
  template:
    metadata:
      labels:
        app: nodejs-todo
    spec:
      containers:
        - name: nodejs-todo
          image: yash5090/nodejs-todo:latest # Replace with the actual image tag
          ports:
            - containerPort: 3000 # Replace with the port your Tetris game listens on
